{% set name = "pycytominer" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycytominer-{{ version }}.tar.gz
  sha256: 3f64cc584b50c80bd2141aab9b3acd77dbd1b651f3764b0d2e03bc963484f1bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - numpy
    - pandas
    - python >=3.4
    - scikit-learn
    - sqlalchemy

test:
  imports:
    - pycytominer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cytomining/pycytominer
  summary: Processing perturbation profiling readouts.
  license: BSD-3-Clause
  license_file: LICENSE.md

outputs:
  - name: pycytominer.collate
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage({{ name|lower }}, exact=True) }}
        - cytominer-database >= 0.3.4

extra:
  recipe-maintainers:
    - gwaybio
