{% set name = "pycytominer" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycytominer-{{ version }}.tar.gz
  sha256: a2b2a1721ec1a40f525fc99a87edadf716dce4faa926b33ba2551f45a13a66ed
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - poetry
    - poetry-dynamic-versioning
  run:
    - python >={{ python_min }},<3.12
    - numpy >=1.16.5
    - scipy >=1.5
    - pandas >=1.2.0
    - scikit-learn >=0.21.2
    - sqlalchemy >=1.3.6,<2
    - pyarrow >=8.0.0
    - csvkit >=1.0.2,<2

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - pycytominer
  commands:
    - pip check

outputs:
  - name: pycytominer
    version: {{ version }}
  - name: pycytominer.collate
    version: {{ version }}
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }},<3.12
        - {{ pin_subpackage('pycytominer', exact=True) }}
        - cytominer_database >=0.3.5
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pycytominer
        - cytominer_database
      commands:
        - pip check
  - name: pycytominer.cell-locations
    version: {{ version }}
    build:
      noarch: python
    requirements:
      host:
        - fire >=0.5.0
      run:
        - python >={{ python_min }},<3.12
        - {{ pin_subpackage('pycytominer', exact=True) }}
        - fsspec >=2023.1.0
        - s3fs >=2023.4.0
        - boto3 >=1.26.79
        - fire >=0.5.0
    test:
      requires:
        - python {{ python_min }}
      imports:
        - pycytominer.cyto_utils.cell_locations

about:
  home: https://github.com/cytomining/pycytominer
  summary: Python package for processing image-based profiling data
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - gwaybio
    - kenibrewer
    - d33bs
