{% set name = "pycytominer" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycytominer-{{ version }}.tar.gz
  sha256: 7a82e9a64f37c3bf96ceb498aab425145b7ca9c4332ec1d0e69e1b37ebab837c
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - numpy
    - pandas
    - python >=3.4
    - scikit-learn
    - sqlalchemy

test:
  imports:
    - pycytominer
  commands:
    - pip check
  requires:
    - pip
outputs:
  - name: pycytominer
    version: {{ version }}
  - name: pycytominer.collate
    version: {{ version }}
    requirements:
      - {{ pin_subpackage('pycytominer', exact=True) }}
      - cytominer_database >=0.3.4

about:
  home: https://github.com/cytomining/pycytominer
  summary: Processing perturbation profiling readouts.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - gwaybio
